### ISSUE TITLE
Allow specifying commit message

### ISSUE THREAD

**Issue by iamogbz** [mislav/bump-homebrew-formula-action#1]
Great work on the github action! Couple minor bugs stopping me from using it.

## Issue

Checks exists on commit message style before allowing merges

## Solution

Allow users specify commit message

---

Open to submitting a PR for this

**Comment by samuelmeuli** [comment]
I agree that it would be nice to have such an option :)

**Comment by mislav** [comment]
@iamogbz That's a good point! I'm open to PRs 🙇
