### ISSUE TITLE
Add the ability to provide a description

### ISSUE THREAD

**Issue by oscarbatori** [mislav/bump-homebrew-formula-action#10]
The current [formula](https://github.com/mislav/bump-homebrew-formula-action/blob/master/src/main.ts) does not seem to provide the ability to specify a description, which is required for a formula bump to be accepted:
<img width="940" alt="Screen Shot 2020-11-05 at 7 21 26 PM" src="https://user-images.githubusercontent.com/1596348/98397193-d120fe80-2013-11eb-9928-2e1c97211a80.png">

**Comment by mislav** [comment]
You can customize the `commit-message` input, which will also be used for PR title & body.

What information does the homebrew-core repository now require for incoming pull requests? I want to update the built-in defaults so these requirements are satisfied with the default value of `commit-message`.

**Comment by oscarbatori** [comment]
@mislav thanks for taking a look. I had to manually enter "New version of Dolt" to get the `needs response` label removed. Maybe insert "automated formula update" as the description or something?

**Comment by mislav** [comment]
@oscarbatori The default commit message body (and thus pull request description) will be:

```
Created by https://github.com/mislav/bump-homebrew-formula-action
```

Would this be enough to satisfy request-info requirements? If so, then our current defaults are sufficient.

**Comment by oscarbatori** [comment]
I am going to see if adding a longer description fixes this, maybe this is too short:
```
commit-message: ${{format('dolt {0}', steps.get_version.outputs.VERSION)}}
```
See this [job](https://github.com/dolthub/dolt/blob/master/.github/workflows/bump-brew-formula.yml) for details.

**Comment by mislav** [comment]
@oscarbatori If you're specifying a custom commit message, it should be at least 3 lines of text instead of 1. Something like:

```
COMMIT SUBJECT

COMMIT BODY
```

This is because the commit subject&body will also become PR title&body, and it seems that the homebrew-core repository requires a PR body.

We should probably add this note to the description of the `commit-message` input in this repo's README. Care to submit a PR?

**Comment by oscarbatori** [comment]
It turns out that the current message that is used both as the issue title and the commit message is correct, and in fact anything else is invalid. This was my original suspicion. See this [issue](https://github.com/Homebrew/homebrew-core/pull/66132) for confirmation. 

We should add that this PR was generated by a plugin to the description of the generated PR, how does that sound?

**Comment by mislav** [comment]
> We should add that this PR was generated by a plugin to the description of the generated PR, how does that sound?

That's what we currently do by default: https://github.com/mislav/bump-homebrew-formula-action/blob/8a3c946ee30515b59963ee79aa36b0382c04ac3a/action.yml#L17-L22

The commit body, and also the pull request description, will be `Created by <URL>`. That's how I submit my PRs to homebrew-core, and they always get accepted.

I don't think we need to change anything in this project, except to note in the documentation that the commit message also becomes the PR message, and that people who change the default should always provide some description. What do you think?

**Comment by mislav** [comment]
Docs added in a72c01367ed5e9bb9e52e765622e73fda72d2bdc
