### ISSUE TITLE
`revision` lines not removed at version bump?

### ISSUE THREAD

**Issue by carlocab** [mislav/bump-homebrew-formula-action#12]
This PR failed `brew audit`: https://github.com/Homebrew/homebrew-core/pull/68188

It seems that it's because the `revision` line was not removed with the version bump: https://github.com/Homebrew/homebrew-core/pull/68188/checks?check_run_id=1637689597#step:7:42

Not sure if this is a peculiarity of this specific PR (it was immediately preceded by two other automated `algernon` version bumps: https://github.com/Homebrew/homebrew-core/pull/68187, https://github.com/Homebrew/homebrew-core/pull/68186), but it would be good to fix it if it wasn't.

**Comment by mislav** [comment]
Thanks for pointing it out! I agree that it would make sense to take out the revision line on a version bump.
