### ISSUE TITLE
Question: Does homebrew-tap input support homebrew's shorthand name?

### ISSUE THREAD

**Issue by jasonkarns** [mislav/bump-homebrew-formula-action#169]
I have a few repos that are using an old version of this action, and they specify the homebrew-tap using homebrew's shorthand (ie, `nodenv/nodenv` instead of the actual repo name of `nodenv/homebrew-nodenv`). They have been working, so this must have been supported at one time.

I'm upgrading these workflows, but since these are release workflows, it's a lot harder to test in advance 😸. I didn't see anything in the releases notes that indicated a breaking change where full github repo name is required. But nor could I find anything in the source code that seemed to allow the shortand (or insert the `homebrew-` prefix if necessary).

The docs imply the shorthand is not supported ("the full GitHub repository name"). Am I assuming correctly the shorthand is no longer supported?

And if it _is_ supported, would `homebrew/core` still trigger the sharding support?

(For reference, this is the reusable workflow I have in-progress with these changes: https://github.com/nodenv/.github/pull/19)

**Comment by mislav** [comment]
As far as I remember, this never supported the shorthand. Some time ago I've noted in the docs that `homebrew-tap` needs to be a full repo name: b5f01a7b22fbd87db67eca3bd3961482e458ec93

`nodenv/nodenv` expanding to the repository name of `nodenv/homebrew-nodenv` is a UI feature of Homebrew that I find to be as confusing as it is useful, and I find no need to reproduce it anywhere else. I feel that all inputs and outputs of GitHub Actions should primarily be following GitHub's naming conventions, not Homebrew's.
