### ISSUE TITLE
Allow to open a PR instead of writing to the main branch directly

### ISSUE THREAD

**Issue by mainrs** [mislav/bump-homebrew-formula-action#17]
This would allow the CI of the tap to run and build all the bottles. home-brew's template for taps does it on each PR. Since the action directly pushes to the branch, the workflow doesn't get triggered and the new bottles aren't getting build

**Comment by mislav** [comment]
Thanks for the suggestion! Agreed that there should be a configuration option to force making a PR even if the authenticating token has write access to the main branch of the repository. 👍
