### ISSUE TITLE
Allow specifying of new version

### ISSUE THREAD

**Issue by iamogbz** [mislav/bump-homebrew-formula-action#2]
## Issue

Currently our bump fails because the download url we specify `https://github.com/tophat/yvm/releases/download/v9.9.9/yvm.js` is not supported by `fromUrl`

https://github.com/mislav/bump-homebrew-formula-action/blob/0ed8358ac317f712ac8d76d584803aae038c4f54/src/version.ts#L31-L34

## Solution

Allow users to specify the version of the new formula this way no parsing need be done on the asset url

### Alternative

1. I see that work is already slated via the `# TODO` flag, implement a more robust version detection from the asset url
1. Allow users to supply a version matching regex that converts part of the asset URL to a version number

---

Open to submitting a PR for this as well

**Comment by mislav** [comment]
Thank you for reporting! I've added support for `https://github.com/REPO/releases/download/TAG/FILE` URLs 🙇
