### ISSUE TITLE
Action fails due to "HttpError: There are merge conflicts"

### ISSUE THREAD

**Issue by matchai** [mislav/bump-homebrew-formula-action#24]
Hi there,

Thank you for your excellent action, Mislav. We've been using it as part of our release process over at https://github.com/starship/starship for a while now.

With the latest release of the action, we started seeing a strange failure with the following error:
```
POST /repos/Homebrew/homebrew-core/forks - 202 in 316ms
POST /repos/matchai/homebrew-core/merge-upstream - 409 in 1071ms
Error: HttpError: There are merge conflicts
```
Full logs: https://github.com/starship/starship/runs/4599656801?check_suite_focus=true#step:2:17

**Comment by mislav** [comment]
@matchai Thank you for reporting. I'll try to address this, but in the meantime, the workaround would be to drop down to git, check out the default branch of `matchai/homebrew-core` and hard-reset it to the latest state of the default branch in upstream.
