### ISSUE TITLE
`tag-name` does not support Changesets format

### ISSUE THREAD

**Issue by john-u** [mislav/bump-homebrew-formula-action#37]
Thanks for the awesome action! We are trying to use this on our monorepo that is versioned and tagged using [Changesets](https://github.com/changesets/changesets) which uses the tag format `packageName@version`. In our case, the tag of the package we want to release is `@smartthings/cli@1.0.0-beta.x`. The action is failing with the following.

```console
Run mislav/bump-homebrew-formula-action@v2
  with:
    tag-name: @smartthings/cli@1.0.0-beta.9
    download-url: https://github.com/john-u/smartthings-cli/releases/download/@smartthings/cli@1.0.0-beta.9/smartthings-macos.tar.gz
    homebrew-tap: https://github.com/john-u/homebrew-smartthings
    commit-message: {{formulaName}} {{version}}
  
  Created by https://github.com/mislav/bump-homebrew-formula-action
  
  env:
    COMMITTER_TOKEN: ***
request
GET /repos/john-u/smartthings-cli/releases/tags/%40smartthings - 404 in 247ms
Error: HttpError: Not Found
```

I've tried numerous input but it looks like it is cutting off after the `/` in the scoped package name (and url encoding it, though not sure that would matter). The reason we can't just let the name default to the currently pushed tag is that changesets will tag each release with [multiple names for each released package](https://github.com/SmartThingsCommunity/smartthings-cli/tags), so the top ref may not be the one we want.

**Comment by mislav** [comment]
Thanks for reporting! Please try out the newest release

**Comment by john-u** [comment]
It made it a little farther, but still fails calling a URL I don't recognize.
```console
Run mislav/bump-homebrew-formula-action@v2
request
GET /repos/john-u/smartthings-cli/releases/tags/%40smartthings%2Fcli%401.0.0-beta.9 - 200 in 118ms
request
GET /repos/john-u/smartthings-cli/releases/assets/69287324 - 302 in 118ms
request
GET /repos/https%3A/ - 404 in 59ms
Error: HttpError: Not Found
```

Here is the run https://github.com/john-u/smartthings-cli/runs/7027429950

**Comment by mislav** [comment]
This shouldn't be a full URL:
```
homebrew-tap: https://github.com/john-u/homebrew-smartthings
```
Try just the `owner/repo` pair

**Comment by john-u** [comment]
Ah, I missed that. It is working as expected now. Thank you for the quick turnaround on this!
