### ISSUE TITLE
Very recent regression: Error: HttpError: Bad credentials

### ISSUE THREAD

**Issue by ssbarnea** [mislav/bump-homebrew-formula-action#48]
While one week ago the action run for the first time succesfully, today it failed with `Error: HttpError: Bad credentials`, even if I am 100% sure I did not reset the token, which was configured to not expire.

https://github.com/ansible/ansible-lint/actions/runs/4186444473/jobs/7254950400

I wonder if this is related to some changes made by gihub. Still, the error is quite opaque.

There is also another possible explanation, the fact that the release was created less than a minute before this action run on the same pipeline. Maybe github have a 401 generic response not due to bad credentials but due to not having time to updates its caches.

Any idea if anyone encountered the same kind of issue? Maybe we need to pull a sleep of like two minutes just to avoid it?

PS. While HTTP "401 Unauthorized" usually indicates lack of permissions it is also often used as generic response for security reasons and to prevent identification of resources. (basically replacing 404)

**Comment by ssbarnea** [comment]
@mislav I generated the token using the new fine-grained security option and gave the "public repo"

![](https://sbarnea.com/ss/Screen-Shot-2023-03-03-13-13-57.56.png)

This seems not to work with this action, even if it it follows instructions regarding what to enable.

**Comment by mislav** [comment]
Hi, I generated a fine-grained token with the same settings as you did and I could access the resource in question without getting a HTTP 401:
```
GH_TOKEN="$(pbpaste)" gh api -i -X HEAD repos/ansible/ansible-lint/tarball/v6.13.0
HTTP/2.0 200 OK
```
Something else is amiss. Perhaps you pasted something wrong when setting the COMMITTER_TOKEN secret?

**Comment by ssbarnea** [comment]
I reset the token and saved it so I can reuse for testing. I tested from CLI and it worked. Still, even after updating the `COMMITER_TOKEN` secret from inside my `release` environment secrets and triggered a rerun of the action, I still got the same error.

https://github.com/ansible/ansible-lint/actions/runs/4355545720/jobs/7612535371

Here is the action usage https://github.com/ansible/ansible-lint/blob/main/.github/workflows/release.yml#L45-L69

- uses 'release` environment where the secret COMMITTER_TOKEN is present
- passes `COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}`

I am not sure what is causing it to fail with 401, maybe I also need to setup `GH_TOKEN` to the same value as as `COMMITTER_TOKEN` ?

Documentation page from https://github.com/mislav/bump-homebrew-formula-action does hints that for public repositories we do not need to configure any `GH_TOKEN` value. 🤷🏽‍♂️

**Comment by mislav** [comment]
> * uses 'release` environment where the secret COMMITTER_TOKEN is present

My guess is that something went wrong with this and that COMMITTER_TOKEN was still null during your workflow run.

**Comment by ssbarnea** [comment]
I release often from this project, so I will find-out in few days. I use release environments for years, never failed me and they are the correct way to setup secrets, instead of "repository secrets", which are available to all jobs (making them unsecure).

**Comment by ssbarnea** [comment]
OMG, I found the issue and I am a little bit embarrassed, when adding the secret, I wrote `COMMITER_TOKEN` instead of `COMMITTER_TOKEN`,... Sorry.
