### ISSUE TITLE
404 due to moved forumla

### ISSUE THREAD

**Issue by amacneil** [mislav/bump-homebrew-formula-action#58]
This action is failing due to homebrew-core forumla being sharded into subdirectories.

- https://github.com/Homebrew/homebrew-core/pull/139592

```
> Run mislav/bump-homebrew-formula-action@v2
GET /repos/amacneil/dbmate/tarball/v2.6.0 - 302 in 95ms
GET /repos/Homebrew/homebrew-core - 200 in [12](https://github.com/amacneil/dbmate/actions/runs/5983141036/job/16239016525#step:2:13)2ms
GET /repos/Homebrew/homebrew-core/branches/master - 200 in 120ms
GET /user - 200 in 76ms
POST /repos/Homebrew/homebrew-core/forks - 202 in 195ms
POST /repos/dbmate-releasebot/homebrew-core/merge-upstream - 200 in 339ms
POST /repos/dbmate-releasebot/homebrew-core/git/refs - 201 in 219ms
GET /repos/dbmate-releasebot/homebrew-core/contents/Formula%2Fdbmate.rb?ref=update-dbmate.rb-[16](https://github.com/amacneil/dbmate/actions/runs/5983141036/job/16239016525#step:2:17)93072004 - 404 in 124ms
Error: HttpError: Not Found
```

[Example failed job](https://github.com/amacneil/dbmate/actions/runs/5983141036/job/16239016525)

**Comment by jtbandes** [comment]
Looks like you can work around this by overriding the `formula-path` action input: https://github.com/mislav/bump-homebrew-formula-action/tree/main#action-inputs

**Comment by amacneil** [comment]
Would be nice to fix this upstream rather than everyone needing to manually override their formula path.

**Comment by mislav** [comment]
Fixed in https://github.com/mislav/bump-homebrew-formula-action/releases/tag/v2.3

Thanks everyone for reporting and @williammartin for suggesting a fix 🎉
