### ISSUE TITLE
Some weird bumping issue

### ISSUE THREAD

**Issue by chenrui333** [mislav/bump-homebrew-formula-action#69]
👋 looks like I just saw some weird formula bumping issues

- https://github.com/Homebrew/homebrew-core/pull/144561 (with v2)
- https://github.com/Homebrew/homebrew-core/pull/144853 (with v3)

I have not dug up yet, but just raise in here. :)

**Comment by sourishkrout** [comment]
let me know if we can help, @chenrui333. just tried another release after merging the workflow gh actions upgrades. thank you!

**Comment by mislav** [comment]
It's a misconfiguration in the runme project.

**Comment by chenrui333** [comment]
Thanks @mislav!
