### ISSUE TITLE
Unexpected input(s) 'download-url'

### ISSUE THREAD

**Issue by extrawurst** [mislav/bump-homebrew-formula-action#7]
even though the readme says this action supports defining the download url I get this warning:

```
##[warning]Unexpected input(s) 'download-url', valid inputs are ['formula-name', 'homebrew-tap', 'commit-message']
```

see: https://github.com/extrawurst/gitui/runs/925402417?check_suite_focus=true

**Comment by mislav** [comment]
Thank you for reporting! [v1.7 now out](https://github.com/mislav/bump-homebrew-formula-action/releases/tag/v1.7) that fixes this 🤘
